apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-local
  template:
    metadata:
      labels:
        app: flask-local
    spec:
      containers:
        - name: flask
          image: localhost:5000/flask-store-app:latest
          ports:
            - containerPort: 5000
